apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-sandbox-test
  labels:
    app: java-sandbox-test
    tags.datadoghq.com/env: sandbox
    tags.datadoghq.com/service: java-sandbox-test
    tags.datadoghq.com/version: v5
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-sandbox-test
  template:
    metadata:
      labels:
        app: java-sandbox-test
        tags.datadoghq.com/env: sandbox
        tags.datadoghq.com/service: java-sandbox-test
        tags.datadoghq.com/version: v5
        admission.datadoghq.com/enabled: "true"
    spec:
      containers:
      - name: java-sandbox-test
        image: schawirin/javasandbox:v1
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
