apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-sandbox
  labels:
    app: java-sandbox
    tags.datadoghq.com/env: sandbox
    tags.datadoghq.com/service: java-sandbox
    tags.datadoghq.com/version: v3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-sandbox
  template:
    metadata:
      labels:
        app: java-sandbox
        tags.datadoghq.com/env: sandbox
        tags.datadoghq.com/service: java-sandbox
        tags.datadoghq.com/version: v3
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64  # Garante que roda apenas em nós com arquitetura amd64
      tolerations:
        - key: "app-arm"
          operator: "Equal"
          value: "sghx"
          effect: "NoSchedule"
      containers:
      - name: java-sandbox
        image: schawirin/hellowork-java:v3
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: java-sandbox-service
spec:
  type: ClusterIP
  selector:
    app: java-sandbox
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: java-sandbox-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: sandbox.yourdomain.com  # Substitua pelo seu domínio real
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: java-sandbox-service
            port:
              number: 80
