jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: eks-latam-deploy  # Vincula ao Environment correto

    steps:
      # 1. Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar as credenciais da AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 3. Atualizar o kubeconfig para EKS
      - name: Update kubeconfig for EKS
        run: aws eks update-kubeconfig --name eks-sales-saleslatam

      # 4. Aplicar o Deployment
      - name: Deploy to EKS
        run: kubectl apply -f k8s/deployment.yaml
