name: Deploy to EKS

on:
  push:
    branches:
      - main  # Executa o workflow em cada push na branch main.

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: eks-latam-deploy  # Referencia o Environment correto

    steps:
      # 1. Checkout do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar a AWS CLI e autenticação com o EKS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Altere para sua região

      - name: Update kubeconfig for EKS
        run: aws eks update-kubeconfig --name <NOME_DO_SEU_CLUSTER>

      # 3. Aplicar o Deployment
      - name: Deploy to EKS
        run: kubectl apply -f k8s/deployment.yaml  # Ajuste o caminho do seu arquivo

      - name: Update kubeconfig for EKS
        run: aws eks update-kubeconfig --name eks-sales-saleslatam

      # 3. Aplicar o Deployment
      - name: Deploy to EKS
        run: kubectl apply -f k8s/deployment.yaml  # Ajuste o caminho do seu arquivo
