name: Deploy Node.js app to EKS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout do código
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Instalar kubectl
    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.24.0' # Ajuste a versão para coincidir com o seu cluster EKS

    # 3. Configurar credenciais da AWS
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Substitua pela região correta do cluster

    # 4. Atualizar o kubeconfig para o cluster EKS
    - name: Update kube config
      run: aws eks update-kubeconfig --name eks-sales-saleslatam

    # 5. Fazer o deploy no cluster
    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
